# Homework 2

## Parker George
### Jan 27, 2025

### Problem 1

In [13]:
def mysum(N):
    if N<0:
        return 1
    elif N==0:
        return 0
    else:
        return N+mysum(N-1)

In [16]:
mysum(10)

55

In [48]:
def mylist(list):
    strlist = []
    intlist = []

    for a in list:
        if type(a) == int or type(a) == float: # checks for type float or int
            intlist.append(a)
        elif type(a) == str: # checks for type str
            strlist.append(a)
    strlist.sort()  # sorts string list
    for i in range(0, len(intlist)):  # sorts the int list
        for j in range(i+1, len(intlist)):
            if intlist[i] >= intlist[j]:
                intlist[i], intlist[j] = intlist[j], intlist[i]

    return intlist+strlist # returns the added list


In [50]:
test = [4,'w',6,8,1,'g',3,-4,0,8,'a','c','z','e']
print(mylist(test))

[-4, 0, 1, 3, 4, 6, 8, 8, 'a', 'c', 'e', 'g', 'w', 'z']


In [70]:
def math(list):
    total = list[0]
    for i in range(1,len(list)-1, 2): # starting at the second item and skipping every other item in the list until the second to last item, this infers that there are just one operator every other number
        operator = list[i]
        operand = list[i+1]

        if operator == '+':
            total += operand
        elif operator == '-':
            total -= operand
        elif operator == '*':
            total *= operand
        elif operator == '/':
            if operand == 0:
                print('division by zero is not allowed')
            total /= operand
        elif operator == '^':
            total **= operand
        else:
            print('operator is not recognized, please try again')
    return total



In [76]:
mathtest = [2, '^',3]
list1d=[2,'^',2,'+',4,'-',5,'*',10]
print(math(mathtest))
print(math(list1d))

8
30


In [73]:
from operator import add, sub, mul, pow, truediv

def pemdas(list):
    precedence = {'+':1, '-':1, '*':2, '/':2, '^':3} # order in which operations must be done
    operations = {'+':add, '-':sub, '*':mul, '/':truediv, '^':pow} # each operator's operation

    def tokens(list): #separates the different items in the list into tokens
        tokens = []
        for item in list:
            if isinstance(item, (int, float)) or item in operations:
                tokens.append(item)
            else:
                print('item is not recognized, please try again')
        return tokens

    def apply(operators, values): # applies an operator to the top two elements in the value stack
        operator = operators.pop()
        b = values.pop()
        a = values.pop()
        values.append(operations[operator](a, b))

    def eval(tokens): # evaluates using 2 stacks, one for the numbers and one for the operators
        values = []
        operators = []

        for token in tokens:
            if isinstance(token, (int, float)):
                values.append(token)
            elif token in operations:
                while (operators and precedence[operators[-1]] >= precedence[token]): # checks the precedence of the operators
                    apply(operators, values)
                operators.append(token)

        while operators: # applies the remaining operators
            apply(operators, values)

        return values[0]

    tokens = tokens(list)
    return eval(tokens) # processes the tokens and evaluates



In [77]:
list1d=[2,'^',2,'+',4,'-',5,'*',10]
list2=[10,'*',3,'^',2,'-',6,'+',4]

print(pemdas(list1d))
print(pemdas(list2))

-42
88


# Problem 2

In [78]:
import numpy as np
def sin(t,n,omega,phi):
    if n==0:
        raise ValueError('n cannot be zero')

    result = np.sin((omega*t)**n+phi)
    return result

In [83]:
time = np.linspace(0,10,10)
sin(time,1,10,np.pi/2)

array([ 1.        ,  0.11527995, -0.97342107, -0.33971181,  0.89509715,
        0.54608532, -0.76919177, -0.7234301 ,  0.6023978 ,  0.86231887])

In [95]:
def quadratic(a,b,c):
    a = np.array(a, dtype=complex)
    b = np.array(b, dtype=complex)
    c = np.array(c, dtype=complex)

    result1 = (-b+np.sqrt(b**2-4*a*c))/(2*a)
    result2 = (-b-np.sqrt(b**2-4*a*c))/(2*a)
    return result1, result2



In [96]:
a = np.array([1,2])
b = np.array([2,3])
c = np.array([1,-1])
quadratic(a,b,c)

(array([-1.        +0.j,  0.28077641+0.j]),
 array([-1.        +0.j, -1.78077641+0.j]))

In [97]:
x_array = np.linspace(-np.pi,np.pi,10)
y_array = np.linspace(0,np.pi*2,10)
z_array = np.linspace(-3,3,10)

x,y,z = np.meshgrid(x_array,y_array,z_array,indexing='ij')

In [98]:
print(x)

[[[-3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265
   -3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265]
  [-3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265
   -3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265]
  [-3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265
   -3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265]
  [-3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265
   -3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265]
  [-3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265
   -3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265]
  [-3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265
   -3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265]
  [-3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265
   -3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265]
  [-3.14159265 -3.14159265 -3.14159265 -3.14159265 -3.14159265
   -3.14159265 -3.14159265 -3.14159265 -3.141592

In [99]:
func = np.sin(x)*(np.cos(y)**2)+z

In [100]:
func

array([[[-3.        , -2.33333333, -1.66666667, -1.        ,
         -0.33333333,  0.33333333,  1.        ,  1.66666667,
          2.33333333,  3.        ],
        [-3.        , -2.33333333, -1.66666667, -1.        ,
         -0.33333333,  0.33333333,  1.        ,  1.66666667,
          2.33333333,  3.        ],
        [-3.        , -2.33333333, -1.66666667, -1.        ,
         -0.33333333,  0.33333333,  1.        ,  1.66666667,
          2.33333333,  3.        ],
        [-3.        , -2.33333333, -1.66666667, -1.        ,
         -0.33333333,  0.33333333,  1.        ,  1.66666667,
          2.33333333,  3.        ],
        [-3.        , -2.33333333, -1.66666667, -1.        ,
         -0.33333333,  0.33333333,  1.        ,  1.66666667,
          2.33333333,  3.        ],
        [-3.        , -2.33333333, -1.66666667, -1.        ,
         -0.33333333,  0.33333333,  1.        ,  1.66666667,
          2.33333333,  3.        ],
        [-3.        , -2.33333333, -1.66666667, -1. 

In [116]:
print(func[0,0,2])

-1.666666666666667
